### ISSUE TITLE
"service-control" change in process results in microk8s commands (refresh-certs, join) failing

### ISSUE THREAD

**Issue by asbalderson** [canonical/charm-microk8s#124]
#### Summary
Deploying the microk8s 1.28/stable  charm, rev 213 charm resulted went into an error state and failed during initial configuration.  It tries to run a few `['microk8s', 'refresh-certs', '-e', 'server.crt']` which return exit status 4 as a Warning, and then finally sets the charm in ERROR state on the same command. Once that error is raised, the charm then goes on to fail running microk8s join which also ends in an error with exit code 6. This error continues through the logs without resolving.

```
2023-10-16 03:07:47 WARNING unit.microk8s/1.peer-relation-changed logger.go:60 error: error running snapctl: snap "microk8s" has "service-control" change in progress
2023-10-16 03:07:47 DEBUG unit.microk8s/1.peer-relation-changed logger.go:60 Failed to restart service microk8s.daemon-kubelite.
2023-10-16 03:07:47 ERROR unit.microk8s/1.juju-log server.go:325 peer:0: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-microk8s-1/charm/./src/charm.py", line 428, in <module>
    main(MicroK8sCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-microk8s-1/charm/venv/ops/main.py", line 454, in __call__
    return main(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-microk8s-1/charm/venv/ops/main.py", line 441, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-microk8s-1/charm/venv/ops/main.py", line 149, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-microk8s-1/charm/venv/ops/framework.py", line 344, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-microk8s-1/charm/venv/ops/framework.py", line 833, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-microk8s-1/charm/venv/ops/framework.py", line 922, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-microk8s-1/charm/./src/charm.py", line 366, in join_cluster
    self.on.config_changed.emit()
  File "/var/lib/juju/agents/unit-microk8s-1/charm/venv/ops/framework.py", line 344, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-microk8s-1/charm/venv/ops/framework.py", line 833, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-microk8s-1/charm/venv/ops/framework.py", line 922, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-microk8s-1/charm/./src/charm.py", line 257, in config_extra_sans
    microk8s.configure_extra_sans(self.config["extra_sans"])
  File "/var/lib/juju/agents/unit-microk8s-1/charm/src/microk8s.py", line 196, in configure_extra_sans
    util.ensure_call(["microk8s", "refresh-certs", "-e", "server.crt"])
  File "/var/lib/juju/agents/unit-microk8s-1/charm/src/util.py", line 103, in ensure_call
    return _ensure_func(run, args, kwargs, subprocess.CalledProcessError)
  File "/var/lib/juju/agents/unit-microk8s-1/charm/src/util.py", line 98, in _ensure_func
    return f(*args, **kwargs)
  File "/var/lib/juju/agents/unit-microk8s-1/charm/src/util.py", line 19, in run
    return subprocess.run(*args, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['microk8s', 'refresh-certs', '-e', 'server.crt']' returned non-zero exit status 4.
```
and

```
2023-10-16 03:08:15 ERROR unit.microk8s/1.juju-log server.go:325 peer:0: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-microk8s-1/charm/./src/charm.py", line 428, in <module>
    main(MicroK8sCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-microk8s-1/charm/venv/ops/main.py", line 454, in __call__
    return main(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-microk8s-1/charm/venv/ops/main.py", line 441, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-microk8s-1/charm/venv/ops/main.py", line 149, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-microk8s-1/charm/venv/ops/framework.py", line 344, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-microk8s-1/charm/venv/ops/framework.py", line 833, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-microk8s-1/charm/venv/ops/framework.py", line 922, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-microk8s-1/charm/./src/charm.py", line 362, in join_cluster
    microk8s.join(join_url, self.config["role"] == "worker")
  File "/var/lib/juju/agents/unit-microk8s-1/charm/src/microk8s.py", line 72, in join
    util.ensure_call(cmd)
  File "/var/lib/juju/agents/unit-microk8s-1/charm/src/util.py", line 103, in ensure_call
    return _ensure_func(run, args, kwargs, subprocess.CalledProcessError)
  File "/var/lib/juju/agents/unit-microk8s-1/charm/src/util.py", line 98, in _ensure_func
    return f(*args, **kwargs)
  File "/var/lib/juju/agents/unit-microk8s-1/charm/src/util.py", line 19, in run
    return subprocess.run(*args, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['microk8s', 'join', '10.246.166.140:25000/6f7d10612912d9a516b1abbcc5a8e0e9']' returned non-zero exit status 6.

```

#### What Should Happen Instead?
The charm should know how and when to run the commands to cluster itself, or report a proper message is a service is hanging or stuck.

#### Reproduction Steps
This is the first time I have seen this bug, I am unable to reproduce at the moment. the bundle for the deployment was this:
```
applications:
  microk8s:
    bindings:
      ? ''
      : oam-space
      control-plane: internal-space
      workers: internal-space
    channel: 1.28/stable
    charm: microk8s
    expose: true
    num_units: 3
    options:
      containerd_custom_registries: '[{ "url": "http://10.245.212.157:5000", "host":
        "docker.io" }]'
      containerd_http_proxy: http://squid.internal:3128
      containerd_https_proxy: http://squid.internal:3128
      containerd_no_proxy: 10.0.0.0/8
      role: control-plane
    series: jammy
    to:
    - '6'
    - '7'
    - '8'
machines:
  '6':
    constraints: tags=microk8s,silo6 zones=zone1
    series: jammy
  '7':
    constraints: tags=microk8s,silo6 zones=zone2
    series: jammy
  '8':
    constraints: tags=microk8s,silo6 zones=zone3
    series: jammy
relations: []
series: jammy
```

#### Environment
This deployment was done on KVM machines, with 4 cores. 20g memory, and a 100G disk.

**MicroK8s charm track**: latest/stable
**Juju version**: 3.3-beta2
**Cloud**: MAAS

#### Additional info, logs
[juju-crashdump-microk8s-2023-10-16-03.09.11.tar.gz](https://github.com/canonical/charm-microk8s/files/12918983/juju-crashdump-microk8s-2023-10-16-03.09.11.tar.gz)
The unit which failed was microk8s-1

**Comment by neoaggelos** [comment]
Thanks for raising the bug @asbalderson. The course of events is most likely this:

- each unit will wait for services to start, then configure certificate SANs using the `refresh-certs` command
- the `refresh-certs` command eventually issues a service restart (`snapctl restart $service`), which will fail with the error message above if another service action is already happening. it happens rarely because this would only happen on extraordinary circumstances.
- the charm will retry the action a few times (10) before claiming defeat and getting into an error state.

I think we need to figure out _what_ breaks and the `microk8s refresh-certs` does not _eventually_ work.

How often do you see this issue occur?

**Comment by asbalderson** [comment]
@neoaggelos So far we have only seen it one time, but I'll keep an eye out for more occurrences and follow up.

**Comment by motjuste** [comment]
Identified another occurrence of this issue.  Logs for this run:  
[juju-crashdump-microk8s-2023-11-18-14.26.17.tar.gz](https://github.com/canonical/charm-microk8s/files/13417476/juju-crashdump-microk8s-2023-11-18-14.26.17.tar.gz)
